//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace OMIS.Server.SensorWS1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZyrhSensorServiceSoap", Namespace="http://www.3gvs.net/")]
    public partial class ZyrhSensorService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadSensorDataInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDeviceHeartbeatTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDeviceStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDeviceSoftwareVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDeviceDebugModeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSettingRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSettingProcessOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSettingResponseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZyrhSensorService() {
            this.Url = global::OMIS.Server.Properties.Settings.Default.OMIS_Server_SensorWS1_ZyrhSensorService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event UploadSensorDataInfoCompletedEventHandler UploadSensorDataInfoCompleted;
        
        /// <remarks/>
        public event UpdateDeviceHeartbeatTimeCompletedEventHandler UpdateDeviceHeartbeatTimeCompleted;
        
        /// <remarks/>
        public event UpdateDeviceStatusCompletedEventHandler UpdateDeviceStatusCompleted;
        
        /// <remarks/>
        public event UpdateDeviceSoftwareVersionCompletedEventHandler UpdateDeviceSoftwareVersionCompleted;
        
        /// <remarks/>
        public event UpdateDeviceDebugModeCompletedEventHandler UpdateDeviceDebugModeCompleted;
        
        /// <remarks/>
        public event UpdateSettingRequestCompletedEventHandler UpdateSettingRequestCompleted;
        
        /// <remarks/>
        public event UpdateSettingProcessCompletedEventHandler UpdateSettingProcessCompleted;
        
        /// <remarks/>
        public event UpdateSettingResponseCompletedEventHandler UpdateSettingResponseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.3gvs.net/HelloWorld", RequestNamespace="http://www.3gvs.net/", ResponseNamespace="http://www.3gvs.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.3gvs.net/UploadSensorDataInfo", RequestNamespace="http://www.3gvs.net/", ResponseNamespace="http://www.3gvs.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadSensorDataInfo(string DeviceCode, string[] MessageList) {
            object[] results = this.Invoke("UploadSensorDataInfo", new object[] {
                        DeviceCode,
                        MessageList});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadSensorDataInfoAsync(string DeviceCode, string[] MessageList) {
            this.UploadSensorDataInfoAsync(DeviceCode, MessageList, null);
        }
        
        /// <remarks/>
        public void UploadSensorDataInfoAsync(string DeviceCode, string[] MessageList, object userState) {
            if ((this.UploadSensorDataInfoOperationCompleted == null)) {
                this.UploadSensorDataInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadSensorDataInfoOperationCompleted);
            }
            this.InvokeAsync("UploadSensorDataInfo", new object[] {
                        DeviceCode,
                        MessageList}, this.UploadSensorDataInfoOperationCompleted, userState);
        }
        
        private void OnUploadSensorDataInfoOperationCompleted(object arg) {
            if ((this.UploadSensorDataInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadSensorDataInfoCompleted(this, new UploadSensorDataInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.3gvs.net/UpdateDeviceHeartbeatTime", RequestNamespace="http://www.3gvs.net/", ResponseNamespace="http://www.3gvs.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateDeviceHeartbeatTime(string DeviceCode, string HeartbeatTime) {
            object[] results = this.Invoke("UpdateDeviceHeartbeatTime", new object[] {
                        DeviceCode,
                        HeartbeatTime});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDeviceHeartbeatTimeAsync(string DeviceCode, string HeartbeatTime) {
            this.UpdateDeviceHeartbeatTimeAsync(DeviceCode, HeartbeatTime, null);
        }
        
        /// <remarks/>
        public void UpdateDeviceHeartbeatTimeAsync(string DeviceCode, string HeartbeatTime, object userState) {
            if ((this.UpdateDeviceHeartbeatTimeOperationCompleted == null)) {
                this.UpdateDeviceHeartbeatTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDeviceHeartbeatTimeOperationCompleted);
            }
            this.InvokeAsync("UpdateDeviceHeartbeatTime", new object[] {
                        DeviceCode,
                        HeartbeatTime}, this.UpdateDeviceHeartbeatTimeOperationCompleted, userState);
        }
        
        private void OnUpdateDeviceHeartbeatTimeOperationCompleted(object arg) {
            if ((this.UpdateDeviceHeartbeatTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDeviceHeartbeatTimeCompleted(this, new UpdateDeviceHeartbeatTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.3gvs.net/UpdateDeviceStatus", RequestNamespace="http://www.3gvs.net/", ResponseNamespace="http://www.3gvs.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateDeviceStatus(string[] DeviceCodeList, int Status) {
            object[] results = this.Invoke("UpdateDeviceStatus", new object[] {
                        DeviceCodeList,
                        Status});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDeviceStatusAsync(string[] DeviceCodeList, int Status) {
            this.UpdateDeviceStatusAsync(DeviceCodeList, Status, null);
        }
        
        /// <remarks/>
        public void UpdateDeviceStatusAsync(string[] DeviceCodeList, int Status, object userState) {
            if ((this.UpdateDeviceStatusOperationCompleted == null)) {
                this.UpdateDeviceStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDeviceStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateDeviceStatus", new object[] {
                        DeviceCodeList,
                        Status}, this.UpdateDeviceStatusOperationCompleted, userState);
        }
        
        private void OnUpdateDeviceStatusOperationCompleted(object arg) {
            if ((this.UpdateDeviceStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDeviceStatusCompleted(this, new UpdateDeviceStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.3gvs.net/UpdateDeviceSoftwareVersion", RequestNamespace="http://www.3gvs.net/", ResponseNamespace="http://www.3gvs.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateDeviceSoftwareVersion(string DeviceCode, string SoftwareVersion, string CrcCode) {
            object[] results = this.Invoke("UpdateDeviceSoftwareVersion", new object[] {
                        DeviceCode,
                        SoftwareVersion,
                        CrcCode});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDeviceSoftwareVersionAsync(string DeviceCode, string SoftwareVersion, string CrcCode) {
            this.UpdateDeviceSoftwareVersionAsync(DeviceCode, SoftwareVersion, CrcCode, null);
        }
        
        /// <remarks/>
        public void UpdateDeviceSoftwareVersionAsync(string DeviceCode, string SoftwareVersion, string CrcCode, object userState) {
            if ((this.UpdateDeviceSoftwareVersionOperationCompleted == null)) {
                this.UpdateDeviceSoftwareVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDeviceSoftwareVersionOperationCompleted);
            }
            this.InvokeAsync("UpdateDeviceSoftwareVersion", new object[] {
                        DeviceCode,
                        SoftwareVersion,
                        CrcCode}, this.UpdateDeviceSoftwareVersionOperationCompleted, userState);
        }
        
        private void OnUpdateDeviceSoftwareVersionOperationCompleted(object arg) {
            if ((this.UpdateDeviceSoftwareVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDeviceSoftwareVersionCompleted(this, new UpdateDeviceSoftwareVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.3gvs.net/UpdateDeviceDebugMode", RequestNamespace="http://www.3gvs.net/", ResponseNamespace="http://www.3gvs.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateDeviceDebugMode(string DeviceCode, int DebugMode) {
            object[] results = this.Invoke("UpdateDeviceDebugMode", new object[] {
                        DeviceCode,
                        DebugMode});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDeviceDebugModeAsync(string DeviceCode, int DebugMode) {
            this.UpdateDeviceDebugModeAsync(DeviceCode, DebugMode, null);
        }
        
        /// <remarks/>
        public void UpdateDeviceDebugModeAsync(string DeviceCode, int DebugMode, object userState) {
            if ((this.UpdateDeviceDebugModeOperationCompleted == null)) {
                this.UpdateDeviceDebugModeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDeviceDebugModeOperationCompleted);
            }
            this.InvokeAsync("UpdateDeviceDebugMode", new object[] {
                        DeviceCode,
                        DebugMode}, this.UpdateDeviceDebugModeOperationCompleted, userState);
        }
        
        private void OnUpdateDeviceDebugModeOperationCompleted(object arg) {
            if ((this.UpdateDeviceDebugModeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDeviceDebugModeCompleted(this, new UpdateDeviceDebugModeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.3gvs.net/UpdateSettingRequest", RequestNamespace="http://www.3gvs.net/", ResponseNamespace="http://www.3gvs.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateSettingRequest(int LogId, int RequestStatus, string RequestTime, string ErrorCode) {
            object[] results = this.Invoke("UpdateSettingRequest", new object[] {
                        LogId,
                        RequestStatus,
                        RequestTime,
                        ErrorCode});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSettingRequestAsync(int LogId, int RequestStatus, string RequestTime, string ErrorCode) {
            this.UpdateSettingRequestAsync(LogId, RequestStatus, RequestTime, ErrorCode, null);
        }
        
        /// <remarks/>
        public void UpdateSettingRequestAsync(int LogId, int RequestStatus, string RequestTime, string ErrorCode, object userState) {
            if ((this.UpdateSettingRequestOperationCompleted == null)) {
                this.UpdateSettingRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSettingRequestOperationCompleted);
            }
            this.InvokeAsync("UpdateSettingRequest", new object[] {
                        LogId,
                        RequestStatus,
                        RequestTime,
                        ErrorCode}, this.UpdateSettingRequestOperationCompleted, userState);
        }
        
        private void OnUpdateSettingRequestOperationCompleted(object arg) {
            if ((this.UpdateSettingRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSettingRequestCompleted(this, new UpdateSettingRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.3gvs.net/UpdateSettingProcess", RequestNamespace="http://www.3gvs.net/", ResponseNamespace="http://www.3gvs.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateSettingProcess(int LogId, string Process, string Time) {
            object[] results = this.Invoke("UpdateSettingProcess", new object[] {
                        LogId,
                        Process,
                        Time});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSettingProcessAsync(int LogId, string Process, string Time) {
            this.UpdateSettingProcessAsync(LogId, Process, Time, null);
        }
        
        /// <remarks/>
        public void UpdateSettingProcessAsync(int LogId, string Process, string Time, object userState) {
            if ((this.UpdateSettingProcessOperationCompleted == null)) {
                this.UpdateSettingProcessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSettingProcessOperationCompleted);
            }
            this.InvokeAsync("UpdateSettingProcess", new object[] {
                        LogId,
                        Process,
                        Time}, this.UpdateSettingProcessOperationCompleted, userState);
        }
        
        private void OnUpdateSettingProcessOperationCompleted(object arg) {
            if ((this.UpdateSettingProcessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSettingProcessCompleted(this, new UpdateSettingProcessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.3gvs.net/UpdateSettingResponse", RequestNamespace="http://www.3gvs.net/", ResponseNamespace="http://www.3gvs.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateSettingResponse(int LogId, int ResponseStatus, string ResponseTime, string ResponseContent, string ErrorCode) {
            object[] results = this.Invoke("UpdateSettingResponse", new object[] {
                        LogId,
                        ResponseStatus,
                        ResponseTime,
                        ResponseContent,
                        ErrorCode});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSettingResponseAsync(int LogId, int ResponseStatus, string ResponseTime, string ResponseContent, string ErrorCode) {
            this.UpdateSettingResponseAsync(LogId, ResponseStatus, ResponseTime, ResponseContent, ErrorCode, null);
        }
        
        /// <remarks/>
        public void UpdateSettingResponseAsync(int LogId, int ResponseStatus, string ResponseTime, string ResponseContent, string ErrorCode, object userState) {
            if ((this.UpdateSettingResponseOperationCompleted == null)) {
                this.UpdateSettingResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSettingResponseOperationCompleted);
            }
            this.InvokeAsync("UpdateSettingResponse", new object[] {
                        LogId,
                        ResponseStatus,
                        ResponseTime,
                        ResponseContent,
                        ErrorCode}, this.UpdateSettingResponseOperationCompleted, userState);
        }
        
        private void OnUpdateSettingResponseOperationCompleted(object arg) {
            if ((this.UpdateSettingResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSettingResponseCompleted(this, new UpdateSettingResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UploadSensorDataInfoCompletedEventHandler(object sender, UploadSensorDataInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadSensorDataInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadSensorDataInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateDeviceHeartbeatTimeCompletedEventHandler(object sender, UpdateDeviceHeartbeatTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDeviceHeartbeatTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDeviceHeartbeatTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateDeviceStatusCompletedEventHandler(object sender, UpdateDeviceStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDeviceStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDeviceStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateDeviceSoftwareVersionCompletedEventHandler(object sender, UpdateDeviceSoftwareVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDeviceSoftwareVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDeviceSoftwareVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateDeviceDebugModeCompletedEventHandler(object sender, UpdateDeviceDebugModeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDeviceDebugModeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDeviceDebugModeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateSettingRequestCompletedEventHandler(object sender, UpdateSettingRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSettingRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSettingRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateSettingProcessCompletedEventHandler(object sender, UpdateSettingProcessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSettingProcessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSettingProcessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateSettingResponseCompletedEventHandler(object sender, UpdateSettingResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSettingResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSettingResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591